namespace Com.CodeGame.CodeWizards2016.DevKit.CSharpCgdk.Model {
    public enum SkillType {
        RangeBonusPassive1,
        RangeBonusAura1,
        RangeBonusPassive2,
        RangeBonusAura2,
        AdvancedMagicMissile,
        MagicalDamageBonusPassive1,
        MagicalDamageBonusAura1,
        MagicalDamageBonusPassive2,
        MagicalDamageBonusAura2,
        FrostBolt,
        StaffDamageBonusPassive1,
        StaffDamageBonusAura1,
        StaffDamageBonusPassive2,
        StaffDamageBonusAura2,
        Fireball,
        MovementBonusFactorPassive1,
        MovementBonusFactorAura1,
        MovementBonusFactorPassive2,
        MovementBonusFactorAura2,
        Haste,
        MagicalDamageAbsorptionPassive1,
        MagicalDamageAbsorptionAura1,
        MagicalDamageAbsorptionPassive2,
        MagicalDamageAbsorptionAura2,
        Shield
    }
}